[project]
name = "scraperpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "camoufox-captcha>=0.1.3",
    "camoufox[geoip]>=0.4.11",
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
]
